name: Kafka demo container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - './**'
      - '!**.adoc'
jobs:
  contracts-rest-service-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/kafka-demo
      tagname: $GITHUB_REF_NAME
      dockerfile: ./Dockerfile
      directory: .
    secrets: inherit    